### ISSUE TITLE
Powershell Gallery slowness: `Install-Module -Name Az` takes 60 minutes instead of 3

### ISSUE THREAD

**Issue by aristosvo** [PowerShell/PowerShellGallery#171]
Hi 👋🏽 

Seems the PowerShell Gallery is very slow today! Didn't know where to report it other than here :)

Operations which take in a normal situation 3 minutes take now 60 minutes, see log file below:

[InstallModule.log](https://github.com/PowerShell/PowerShellGallery/files/6769930/InstallModule.log)

**Comment by adityapatwardhan** [comment]
Thank you for reporting. We are having a look.

**Comment by emarzanoBNY** [comment]
I'll second this.  Also experiencing this issue.

**Comment by adityapatwardhan** [comment]
We had some issues with CDN and now believe the slowness has been fixed, please let us know if this is not the case anymore.

**Comment by aristosvo** [comment]
This looks like it used to be, thanks for the fix! 🎉

**Comment by aristosvo** [comment]
Seems to recur..!

**Comment by pucciniplagiarist** [comment]
Yes the issue is still present this morning.

**Comment by anamnavi** [comment]
Hi @aristosvo, @pucciniplagiarist thanks for reaching out. We are aware of this and the Gallery CDN availability should have stabilized by now. We are investigating into the root cause of this. You can follow the status of the gallery at this link: https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md

**Comment by aristosvo** [comment]
@anamnavi I don't know how it's possible, but our downloads are still taking 15 minutes instead of 3 previously..

**Comment by vercellone** [comment]
Just over an hour ago: `Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force`

Elapsed time: 0:40:28.8844

**Comment by gautamdsheth** [comment]
@aristosvo - can you please reopen the issue ? It is happening with us as well !

@anamnavi - saw the status page, it shows that the CDN issue is resolved, but its not.

**Comment by aristosvo** [comment]
@gautamdsheth I can’t, sorry! You can open a new one if you want to!!

**Comment by anamnavi** [comment]
We're working on a more long term fix for this since it's a long term issue. I re-opened the issue.

**Comment by dhekimian** [comment]
I noticed on a fresh Windows 2019 build that it was extremely slow also but after upgrading key packages, installing ALL PowerShell Modules were significantly faster. 

I was able to install the AZ Module in ~5 minutes after updating the relevant PowerShell packages.

Via [Chocolatey](https://chocolatey.org/), it took less than 30 seconds to download and install all the AZ Modules. YMMV

I found 3 different solutions:
## 1. Update PowerShell Packages/Modules (Works for All PowerShellGallery Module Installs)

**To check versions of installed modules:**
``` powershell
Get-Module -ListAvailable
or
Get-Module -Name PowerShellGet
```

**To update the relevant packages:**
``` powershell
Write-Output ==^> Install latest NuGet
Install-PackageProvider NuGet -Force

Write-Output ==^> Set PowerShell Gallery to Trusted
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

Write-Output ==^> Install latest PowerShellGet
# *PowerShellGet* also updates its dependency *PackageManagement*
Install-Module PowerShellGet -Force

Write-Output ==^> Install latest PSReadLine
Install-Module PSReadLine -Force
```
## 2. Install Azure PowerShell Module via MSI Package
You need to find the AZ release version you want to install and download it. 
- GitHub Repo for MSI  - https://github.com/Azure/azure-powershell
- Releases Page - https://github.com/Azure/azure-powershell/releases
- 6.2.1 Release:  https://github.com/Azure/azure-powershell/releases/tag/v6.2.1-July2021 (look under Assets)
- 6.2.1 MSI Download Link: https://github.com/Azure/azure-powershell/releases/download/v6.2.1-July2021/Az-Cmdlets-6.2.1.34515-x64.msi

## 3. Install Azure PowerShell Module via Chocolatey
- Azure PowerShell Chocolatey Package - https://community.chocolatey.org/packages/az.powershell
- `choco install az.powershell`
- `choco install az.powershell --version=5.9.0` (If you need a specific version)

**Comment by bcassell** [comment]
Still having issues with this today.  Do we have any timeline on this?  Thanks.

**Comment by psyrus** [comment]
Facing this on our side too. 20 minutes to install Az.Accounts (5.x megabytes) :(

**Comment by kaburkett** [comment]
This slowness is an issue for me today.

**Comment by fsckyes** [comment]
Experiencing extreme slowness as well

**Comment by jasonpnnl** [comment]
We are experiencing the same thing, which is a problem when using managed dependencies with Azure Functions. The download of managed dependencies from psgallery doesn't complete before the function execution timeout is reached.

**Comment by alerickson** [comment]
We're working on a long term solution for this.  We've had consistent issues with our database connection pools maxing out, we've restarted our instances to reset the connection pools and this should provide a temporary solution.  We'll continue to restart our instances if/when this issue arises so that there's minimal interruption until we have our permanent fix.

**Comment by daltonscole** [comment]
Running into issues with this today using Azure Functions managed dependencies, it times out while downloading modules and causes the function to fail.

**Comment by aristosvo** [comment]
@alerickson It's really horrible at the moment 😢

**Comment by Robulane** [comment]
Same here today, extremely slow

**Comment by dchasman** [comment]
Same here

**Comment by rdelcampog** [comment]
Same here :(

**Comment by axel-dd** [comment]
Still extremely slow. Is there any solution in the pipeline? This problem has existed for months. 

![image](https://user-images.githubusercontent.com/6698567/148401572-fe493614-cef9-41e2-a61e-7915aa673214.png)

**Comment by SQLCanuck** [comment]
Having the horrible performance issues now as well.  Given this is backed by Microsoft, is this not using Azure auto scale features to avoid such problems???

**Comment by monken** [comment]
It's been really bad as of late. Any plans for improvements? Since version 7.0.0, I now download and install through the released bundle from github:

```shell
PSAz=$(curl -sL https://api.github.com/repos/Azure/azure-powershell/releases/latest | jq -r '.assets[].browser_download_url | select(. | endswith(".tar.gz"))')

mkdir -p /tmp/azcmdlets
curl -Lso /tmp/azcmdlets/az.tar.gz $PSAz
tar -xzf /tmp/azcmdlets/az.tar.gz -C /tmp/azcmdlets
pwsh /tmp/azcmdlets/InstallModule.ps1
```

**Comment by axel-dd** [comment]
@monken Thanks for sharing your workaround. I also use it now.

**Comment by gautamdsheth** [comment]
Hello, is there any progress on this issue ?  Has been quite bad nowadays.
Took 50 mins today

![image](https://user-images.githubusercontent.com/8832018/153207884-b7c93148-5b5b-4679-9f43-9c41b42cb771.png)

**Comment by ekdegerman** [comment]
We have the same issue when trying to install the Az module in hosted jobs running on windows-latest (still Windows Server 2019 so far) in Azure pipelines. Seems downloading it from github instead as @monken suggested makes it a lot more reliable so we'll be using that workaround at least until there is a resolution here.

**Comment by nzh10** [comment]
Have same issue here. The downloading speed is extremely slow, and does not have any output... I can't even provide debugging information for diagnosis :(

**Comment by archonandrewhunt** [comment]
Having this issue today, let it run for 30+ minutes before giving up

**Comment by neman** [comment]
Extreme slow installation. I gave up and used `choco install az.powershell`

**Comment by daojah** [comment]
Same issue today

**Comment by bjh1977** [comment]
Me too

**Comment by pari205** [comment]
Same issue, the following command hangs, any solution?
Install-Module -Name Az -AllowClobber -Force

**Comment by daojah** [comment]
> Same issue, the following command hangs, any solution? Install-Module -Name Az -AllowClobber -Force

Just wait)  It's helped me

**Comment by aroramaxus** [comment]
Same issue. taking circa 50 mins. I have tried the following as recommended:

Write-Output ==^> Install latest NuGet
Install-PackageProvider NuGet -Force

Write-Output ==^> Set PowerShell Gallery to Trusted
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

Write-Output ==^> Install latest PowerShellGet
# *PowerShellGet* also updates its dependency *PackageManagement*
Install-Module PowerShellGet -Force

Write-Output ==^> Install latest PSReadLine
Install-Module PSReadLine -Force

then doing 

 Install-Module -Name Az

**Comment by nexxuno** [comment]
Having the same problem, any news @alerickson  ? almost a year now

**Comment by smflorentino** [comment]
I had the same issue and updated NuGet from 5.9 to 6.1. That helped a lot:
`nuget update -self`

**Comment by Bv-Lucas** [comment]
Hello guys 

It's been almost a year and still seems to be a recurring issue. Sometimes run below 10m, sometimes takes more than 1 hour !!!! And it happens very often.

Just to install ps az module, honestly this is not acceptable, I'm reaching azure devops pipeline timeout randomly due to this slowness on a build that supposedly takes lower than 10minutes 

I just can't rely on PS Gallery when a task can take anywhere from 5 minutes to 1hour (+) according to download throttle. 

Is there anything planned to address this or should we move away from the official PSGallery ?

**Comment by Bv-Lucas** [comment]
> I found running the install with `-Verbose` logging on seemed to help, maybe give that a shot if you encounter this?

I always run it with verbose, apart from seeing every package taking ages to download it doesn't make any difference to me :/

**Comment by ajacks88** [comment]
Running into this issue today. We install the az module as a part of some of our builds and for those its sometimes taking quite a long time/breaking the deployment if it takes too long.

**Comment by psyrus** [comment]
We gave up on the PSGallery as a reliable source especially for the larger AZ modules.

Hopefully our workaround can help anyone considering alternatives. We first tried with the Azure Artifacts Repo from ADO but hilariously that is also spotty (it will just fail the pipeline 1/20 times roughly). Ended up going with an Azure Storage Account.

```powershell
#region Stage the AZ files

$moduleCacheStorageId = $originalParameters.azModuleCacheStorageAccountResourceId.value
$solutionRoot = Split-Path -Path $PSScriptRoot -Parent
$dockerFolder = Join-Path -Path $solutionRoot -ChildPath 'docker' -Resolve

if ($moduleCacheStorageId) {
  $storageSubscription, $storageRg, $storageName = $moduleCacheStorageId -split '/' | Select-Object -Index 2, 4, 8
  $currentSubId = (Get-AzContext).Subscription.Id
  if ($currentSubId -eq $storageSubscription) {
    $storageAccount = Get-AzStorageAccount -ResourceGroupName $storageRg -Name $storageName
    $strgContext = $storageAccount.Context
    $containerName = 'az-modules'
  }
}
# First check for the existence of the package in the storage account, if it exists then download it and unzip
$azModuleVersions = $originalParameters.azModuleVersions.value
foreach ($v in $azModuleVersions) {
  Write-Information -MessageData "Pulling down [$v] version of Az module set"
  $filePrefix = "az_$($v)"
  $fileName = "$filePrefix.zip"
  $saveDestinationParent = Join-Path -Path $dockerFolder -ChildPath 'az_versions'
  $saveDestination = Join-Path -Path $saveDestinationParent -ChildPath $filePrefix
  # First check with the blob version
  if ($storageAccount) {
    $blobRef = Get-AzStorageBlob -Container $containerName -Blob $fileName -Context $strgContext -ErrorAction SilentlyContinue
    if ($blobRef) {
      Write-Information -MessageData 'Retreiving Az module version from storage cache'
      $null = Get-AzStorageBlobContent -Blob $fileName -Destination $fileName -Context $strgContext -Container $containerName -Force
      Expand-Archive -Path $fileName -DestinationPath $saveDestinationParent -Force
      Remove-Item -Path $fileName
    } else {
      Write-Information -MessageData 'Downloading Az module from PSGallery and saving to storage cache'
      # Get from PS Gallery Save to Disk
      Save-Module -Name Az -LiteralPath $saveDestination -RequiredVersion $version -Force -Repository PSGallery

      # Zip
      Compress-Archive -Path $saveDestination -DestinationPath $fileName

      # Push to blob storage
      Set-AzStorageBlobContent -File $fileName -Container 'az-modules' -Context $strgContext
      Remove-Item -Path $fileName
    }
  } else {
    Write-Information -MessageData 'Downloading Az module from PSGallery'
    Save-Module -Name Az -LiteralPath $filePrefix -RequiredVersion $version -Force -Repository PSGallery
  }
}

#endregion Stage the AZ files
```

**Comment by SydneyhSmith** [comment]
We made a recent update to the Gallery, are folks seeing any improvements in installation times for Az? Thanks!

**Comment by nexxuno** [comment]
Our pipeline (that uses Az-install in multiple places) went from 3hours to 13minutes, it was either a lucky run or your fix worked. Thanks.

**Comment by eosho** [comment]
This is still an issue for me. I am running an image build pipeline that installs some prerequisite modules. Without the Az module, my pipeline takes ~30 mins and with the AZ module almost ~2 hours.

I am running this via Microsoft hosted agent in ADO.

**Comment by INuvanda** [comment]
I am experiencing the same issue.

**Comment by draganya** [comment]
Having the same issue atm, and not just with this module.

**Comment by vishnumenikkara** [comment]
Hello, I am facing extreme slowness while installing modules with PowerShell Gallery. Can someone please take a look.

**Comment by lubaihua33** [comment]
I also hit she same issue these days.

**Comment by quintennoels** [comment]
Even though the installation says it's complete, it continues in the background for tens of minutes. 30mins +. How is this still not resolved..

**Comment by patrickmoore-nc** [comment]
Same problem here from PowerShell core on Ubuntu. This is terrible.

**Comment by neilmca-inc** [comment]
Just trying this now on my laptop locally in Windows Terminal > PowerShell ....

`Update-Module -Name Az -Force`

and it's already been running for 30+ minutes - what is happening here?

**Comment by anamnavi** [comment]
@neilmca-inc We had a brief unavailability for 5-10 mins at 11:43pm PST (5/16) and 12:47am PST (5/17) but Gallery should be good and fully available now, are you still finding slowness with Update-Module @neilmca-inc?

**Comment by jpawlowski** [comment]
Yea, it is very slow here still in Europe/Germany ... :-/
Could you have a look once more please @anamnavi ?

**Comment by tbish967** [comment]
Seeing this as well coming from GitHub Actions - installing 4 Az submodules is taking 10 minutes, and the slowness looks like it's causing Artifactory to crash out. Is there any workaround for this?

**Comment by oletho** [comment]
Right now I am running Update-Module Az.* and passing 90 minutes...
Denmark/Europe

**Comment by AlexHimself** [comment]
I'm also experiencing very long update times. I had to do `-Verbose` to make sure it was even working.

It seems like the update process could be faster if it downloaded everything locally and then installed it. It looks like it's doing each piece one at a time.

**Comment by SQLCanuck** [comment]
@AlexHimself you could give Install-PSResource a try, in PS 7.4. It seemed to install the Az module much faster for me, it could have been chance but worth a shot.

**Comment by AlexHimself** [comment]
> @AlexHimself you could give Install-PSResource a try, in PS 7.4. It seemed to install the Az module much faster for me, it could have been chance but worth a shot.
> 
> https://learn.microsoft.com/en-ca/powershell/module/microsoft.powershell.psresourceget/install-psresource?view=powershellget-3.x

I'll check it out. I'm actually curious if the issue is `OneDrive`, which is mapped to the same "Documents" directory and is messing with the files constantly. Uninstalling the module caused OneDrive to bark about hundreds of files being soft deleted.

I'm not seeing a straightforward way to move the `PSModulesPath` and also have `Install-Module` land new modules there. Still troubleshooting but if true, **OneDrive** seems like it could be a problem for everyone using it?

**Comment by wopie-rw** [comment]
Currently seeing delays when running `Install-Module -Name Az` in my ADO pipeline. This module install went from taking 1-2 minutes to 20+ minutes (and in one instance, failing after 20+ minutes). I'm hoping this is related to [today's maintenance window](https://github.com/PowerShell/PowerShellGallery/blob/master/psgallery_status.md), although this is occurring quite a bit earlier than the scheduled window.

**Comment by MartinM85** [comment]
I'm facing the same issue with Microsoft.Graph module. Download of all packages is fast, but the installation takes hours until it times out

> WARNING: "Provider 'PowerShellGet' is not completing the request in the time allowed; Canceling request.

**Comment by erickwatson** [comment]
Having the same issue here. In fact, all installations are taking longer than they should.
